name: Update - Gradle Wrapper
on:
  workflow_dispatch:
  schedule:
    # Check updates every 2nd Tuesdays on 6AM UTC
    - cron: 0 6 */14 * TUE

jobs:
  gradle_update:
    name: Gradle Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: develop
      - name: Gradle Wrapper Check
        uses: gradle-update/update-gradle-wrapper-action@v1.0.13
        with:
          reviewers: PhilippHeuer, iProdigy
          labels: dependencies
          base-branch: develop
          target-branch: develop
